version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}CA_recomend_sistem-api
    build:
      context: .
      dockerfile: CA_recomend_sistem-api/Dockerfile
    links:
        - db
    ports:
        - 5000:8080
        - 5001:8081


  db:
    container_name: "db"
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Qwerty123!"
        ACCEPT_EULA: "Y"
